# UI BUILD and PUSH

steps:
- name: 'gcr.io/cloud-builders/docker'
  id: UI-Build
  args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/${PROJECT_ID}/devdock-ui-release:$TAG_NAME', '.']

- name: 'gcr.io/cloud-builders/docker'
  id: UI-Push
  args: ['push', 'gcr.io/${PROJECT_ID}/devdock-ui-release:$TAG_NAME']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'devdock-ui'
    - '--image=gcr.io/${PROJECT_ID}/devdock-ui-release:$TAG_NAME'
    - '--platform=managed'
    - '--region=us-central1'
    - '--allow-unauthenticated'
    - '--port=80'
    # - '--set-env-vars=KEY=VALUE'